[server]
fileWatcherType = "watchdog"
runOnSave = true
headless = true
port = 8501
address = "0.0.0.0"

[theme]
primaryColor = "#7C3AED"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
enableXsrfProtection = true